apiVersion: v1
kind: Service
metadata:
  name: example_service_name
  namespace: example_service_namespace
spec:
  type: NodePort
  selector:
    app: example_app_01
  ports:
    - protocol: TCP
      port: 3456
      targetPort: http
